export let alias = {
    area_demography_1population: "Загальна кількість населення",
    area_demography_2density: 'Щільність населення',
    area_demography_rivenurbanizatsii: 'Рівень урбанізації',
    area_demography_3mentowomen: 'Співвідношення чоловіків до жінок',
    area_demography_utrymantsinapratsuuchoho: 'Кількість утриманців на одного працюючого',
    area_demography_zminachiselnostinaselennya: 'Зміна чисельності населення',
    area_sotspol_vyplachenipensii: 'Загальний обсяг виплачених пенсій',
    area_budgets_1dohodymistsevogobudget: 'Доходи місцевих бюджетів',
    area_budgets_2pdfonadushu: 'ПДФО на одну особу',
    area_budgets_3ttranfertynadushu: 'Трансферти на одну особу',
    area_budgets_zempod: 'Земельний податок та плата за оренду землі на 1 га загальної земельної площі',
    area_budgets_rivpodnavnadushu: 'Рівень податкового навантаження на одну особу',
    area_budgets_rivfinzalejnosti: 'Рівень фінансової залежності місцевого бюджету',
    area_budgets_chastkapodatknadhodj: 'Частка податкових надходжень',
    area_budgets_chastkanepodatknadhodj: 'Частка неподаткових надходжень',
    area_demography_serednviknasel: 'Середній вік населення території',
    area_demography_8chastkavikomst60:'Частка осіб віком старше 60 років',
    area_demography_7chastkavikomst3560: 'Частка дорослих віком від 35 до 60 років',
    area_demography_6chastkavikomst1834:'Частка молоді віком від 18  до 34 років',
    area_demography_5chastkavikomst617:'Частка дітей віком від 6 до 17 років',
    area_demography_4chastkavikomst05:'Частка дітей віком від 0 до 5 років',
    area_sotspol_vydatkynannadannyapilg:'Видатки на надання пільг',
    area_sotspol_vydatkynannadannyasubs:'Видатки на  надання субсидій',
    area_sotspol_kilkistpensioner:'Кількість пенсіонерів',
    point_derguprav_law_sud:'Суди',
    law:'Суди',
    '2comun':'Комунальна інфраструктура',

    point_infrastructure_2comun_jek:'Житлово-експлуатаційні підприємства',
    point_infrastructure_1zvyazok_1post:'Відділення УДППЗ "Укрпошта"',
    '1zvyazok':"Підприємства зв'язку",
    point_infrastructure_1zvyazok_inshi:"Інші оператори поштового зв'язку",
    point_infrastructure_2comun_pidprblago:'Підприємства з благоустрою',
    point_infrastructure_3tranport_aviacompany:'Авіакомпанії',
    point_infrastructure_3tranport_porty:'Порти',
    '3tranport':'Транспортні підприємства',
    point_demography_obyednannyahromadyan_proffspilky:'Профспілки',
    obyednannyahromadyan:"Об'єднання громадян",
    point_education_naukzaklady_naukovizaklads:'Наукові заклади',
    naukzaklady:'Наукові заклади',
    point_ekologyy_ekolnebezpobject_ekolnebezpobjects:"Екологічно небезпечні об'єкти",
    ekolnebezpobject:"Екологічно небезпечні об'єкти",
    point_sotspol_1sotshelp_2tsentrsocobsl:'Центри соціального обслуговування',
    '1sotshelp':'Заклади та установи сфери соціального захисту',
    point_sotspol_1sotshelp_1tsentrzayn:'Центри зайнятості',
    point_sotspol_1sotshelp_3inshosotszaklady:'Інші соціальні заклади',
    '1zaklohorzd':"Заклади охорони здоров'я",
    point_ohorzdorov_1zaklohorzd_ambulator:'Амбулаторно-поліклінічні заклади',
    point_ohorzdorov_1zaklohorzd_likarny:'Лікарняні заклади',
    point_ohorzdorov_1zaklohorzd_medsotsz:'Заклади медико-соціального захисту',
    point_ohorzdorov_1zaklohorzd_sanprofzaklad:'Санаторно-профілактичні заклади',
    point_ohorzdorov_1zaklohorzd_sanatoryi:'Санаторно-курортні заклади',
    point_ohorzdorov_1zaklohorzd_zaklperelevkrov:'Заклади переливання крові',
    point_osvitaa_pshk_pozashkilny:'Позашкільні навчальні заклади',
    pshk:'Позашкільні навчальні заклади',
    point_osvitaa_profteh_ptu:'Професійно-технічні навчальні заклади',
    profteh:'Професійно-технічні навчальні заклади',
    point_osvitaa_doshhkilnzakl_doshkilnyzaklady:'Дошкільні навчальні заклади',
    doshhkilnzakl:'Дошкільні навчальні заклади',
    point_osvitaa_heducat_coledg:'Коледжі',
    heducat:'Вищі навчальні заклади',
    point_osvitaa_heducat_institute:'Інститути',
    point_osvitaa_heducat_univercity:'Університети',
    point_osvitaa_heducat_academyi:'Академії',
    point_osvitaa_heducat_zpo:'Заклади післядипломної освіти',
    point_energyy_teploenergy_teplopostachalnypidpr:'Теплопостачальні підприємства',
    teploenergy:'Теплоенергія',
    point_energyy_altobj_alternatyvenergobj:"Об'єкти альтернативної енергетики",
    altobj:"Об'єкти альтернативної енергетики",
    point_energyy_elektroenergy_elektropostachalnicompany:'Електропостачальники',
    elektroenergy:'Електроенергія',
    point_energyy_elektroenergy_pidprvyrobnutstvaenergii:'Підприємства з виробництва електроенергії',
    point_culturee_zakladyfizkultury_zakladyfizkultury:'Заклади фізкультури',
    zakladyfizkultury:'Заклади фізичної культури та спорту',
    point_culturee_vydavntamedia_knygarnivydavnystva:'Видавництва та книгарні',
    vydavntamedia:'Видавництво та медіа',
    point_culturee_vydavntamedia_drukovanizmi:'Друковані ЗМІ',
    point_culturee_vydavntamedia_teleradiocompanii:'Телерадіокомпанії',
    point_culturee_1cultzaklady_1museum:'Музеї',
    '1cultzaklady':'Заклади культури',
    point_culturee_1cultzaklady_2theatre:'Театри',
    point_culturee_1cultzaklady_3library:'Бібліотеки',
    point_culturee_1cultzaklady_4inshizaklady:'Інші заклади культури',
    point_osvitaa_1zosh_2school1:'ЗОШ I ступенів',
    '1zosh':'Загальноосвітні навчальні заклади',
    point_osvitaa_1zosh_3school12:'ЗОШ I-II ступенів',
    point_osvitaa_1zosh_1school13:'ЗОШ I-III ступенів',
    point_osvitaa_1zosh_4school23:'ЗОШ II-III ступенів',
    point_osvitaa_1zosh_internatschool:'ЗОШ-інтернати',
    point_osvitaa_1zosh_vechirnyschool:'Вечірні школи',
    point_osvitaa_1zosh_spetsializovanyschool:'Спеціалізовані школи',
    point_osvitaa_1zosh_himnasium:'Гімназії',
    point_osvitaa_1zosh_licey:'Ліцеї',
    point_osvitaa_1zosh_colegium:'Колегіуми',
    point_osvitaa_1zosh_spetsialnyschool:'Спеціальні школи',
    area_ekonomika_rivenbezrobittya:'Рівень безробіття',
    area_ekonomika_kilkistbezrobitnyh:'Кількість безробітних',
    area_budgets_chastkadohodvidoperatsiyzkapitalom:'Частка доходів від операцій з капіталом',
    area_sotspol_sumvydatkynasotszahyst:'Загальна сума видатків на соціальний захист',
    area_sotspol_vydatkynasotszahystnadushu:'Видатки на соціальний захист в розрахунку на одну особу',
    area_sotspol_pytomavagavydatkivnasotszahyst:'Питома вага видатків на соціальний захист',
    area_ekonomika_capitalinvest:'Капітальні інвестиції',
    area_ekonomika_vrp:'ВРП у фактичних цінах',
    area_ekonomika_vrpnadushu:'ВРП на одну особу',
    area_ekonomika_ekonomaktyvnnaselennya:'Економічно активне населення',
    area_budgets_kapitalvidbudget:'Капіталовкладення у відсотках від загальних витрат бюджету',
    area_budgets_rentazalisresurs:'Рента за використання лісових ресурсів в доходах місцевих бюджетів',
    area_zemres_chastkasgzemel:'Частка сільськогосподарських земель',
    area_zemres_chastkspai:'Частка розпайованих земель сільськогосподарського призначення',
    area_zemres_avgareapai:'Середня площа земельної ділянки-паю',
    area_osvitaa_vydatkynadushunas:'Видатки з місцевого бюджету на освіту в розрахунку на одну особу',
    area_osvitaa_pytomavahavydatkiv:'Питома вага видатків на освіту у складі видатків бюджету',
    area_osvitaa_vydatkynashkolyara:'Видатки з місцевого бюджету на загальноосвітні навчальні заклади в розрахунку на 1 дитину шкільного віку',
    area_ohorzdorov_vydatkynadushu:"Видатки місцевого бюджету на охорону здоров'я в розрахунку на одну особу",
    area_ohorzdorov_pytomavahavydatkiv:"Питома вага видатків на охорону здоров'я у складі видатків бюджету",
    area_ohorzdorov_vydatky:"Видатки місцевого бюджету на охорону здоров'я",
    area_osvitaa_vydatky:'Видатки місцевого бюджету на освіту',
    area_culturee_vydatkyvse:'Видатки місцевого бюджету на духовний і фізичний розвиток людини',
    area_culturee_vydbiblioteky:'Видатки місцевого бюджету на бібліотеки',
    area_culturee_vydmuseum:'Видатки місцевого бюджету на музеї, виставки, заповідники',
    area_culturee_vydclub:'Видатки місцевого бюджету на палаци та будинки культури, клуби та інші заклади клубного типу',
    area_culturee_vydteatry:'Видатки місцевого бюджету на творчі спілки, театри, філармонії, гастрольну діяльність',
    area_culturee_vydzakhody:'Видатки місцевого бюджету на інші культурні та мистецькі заклади та заходи',
    area_culturee_vydtv:'Видатки місцевого бюджету на телебачення і радіомовлення',
    area_culturee_vydgazety:'Видатки місцевого бюджету на періодичні видання (газети та журнали)',
    area_culturee_vydknyhovydannya:'Видатки місцевого бюджету на книговидання',
    area_culturee_vydinshe:'Видатки місцевого бюджету на інші засоби масової інформації',
    area_culturee_vydfizra:'Видатки місцевого бюджету на фізичну культуру та спорт',
    aptpunkt:'Аптечні пункти',
    point_ohorzdorov_aptpunkt_apteky:'Аптечні пункти',
    area_demography_koefnarodj: 'Коефіцієнт народжуваності',
    area_demography_koefsmertnosti:'Коефіцієнт смертності',
    area_demography_pryrodpryrist:'Природний приріст населення',
    area_demography_migrpryrist:'Міграційний приріст населення',
    area_demography_zminanasel: 'Зміна чисельності населення',
    area_demography_ekonomaktyv : 'Частка економічно активного населення',
    area_zemres_1zagarea : 'Загальна площа території',
    area_zemres_sgzemli : 'Площа земель сільськогосподарського призначення',
    area_zemres_lisovizemli : 'Площа земель лісогосподарського призначення',
    area_zemres_derjavnizemli : 'Площа земельних ділянок державної власності',
    area_zemres_komunalnizemli : 'Площа земельних ділянок комунальної власності',
    area_zemres_chastkaderjavnyh : 'Частка земельних ділянок державної власності',
    area_zemres_chastkakomunalnyh : 'Частка земель комунальної власності',
    area_zemres_chastkapryvatnyh :' Частка земель приватної власності',
    area_zemres_pryvatnizemli : 'Площа земельних ділянок приватної власності',
    area_zemres_rekreaciyazemli : 'Площа рекреаційних територій',
    area_zemres_chastkalisovi:'Частка земель  лісогосподарського призначення',
    area_zemres_chastkajytlova:'Частка земель житлової та громадської забудови',
    area_zemres_chastkapromyslovyh : "Частка земель, що використовуються підприємствами промисловості, енергетики, транспорту та зв’язку",
    area_promislovist_obsyahprod :' Обсяги реалізації промислової продукції',
    area_promislovist_kilkistpracivnykiv : 'Кількість працівників, зайнятих у промисловості',
    area_infrastructure_gkhvdtk:'Видатки місцевого бюджету на житлово-комунальне господарство',
    area_ekonomika_kilkzaynyatyh: 'Зайняте населення',
    area_ekonomika_indexspozhyvchyhtsin:'Індекс споживчих цін',
    area_sotspol_vyddopomohakompensacii:'Видатки на виплату соціальних допомог та компенсацій',
    area_sotspol_vydatkyinshe : 'Інші видатки на соціальний захист та соціальне забезпечення',
    area_ohorzdorov_vydatkylikarni:'Видатки місцевого бюджету на лікарні, санаторії та станції переливання крові',
    area_ohorzdorov_vydatkypolohovibudynky:'Видатки місцевого бюджету на пологові будинки та будинки дитини',
    area_ohorzdorov_vydatkypolikliniky:'Видатки місцевого бюджету на поліклініки і амбулаторії',
    area_ohorzdorov_vydatkyfeldsherski:'Видатки місцевого бюджету на фельдшерсько-акушерські пункти',
    area_ohorzdorov_vydatkyinshi:"Інші видатки місцевого бюджету на охорону здоров'я",
    area_osvitaa_vydatkydoshkilni:'Видатки місцевого бюджету на дошкільні заклади освіти',
    area_osvitaa_vydatkyshkoly:'Видатки місцевого бюджету на загальноосвітні, вечірні, школи та школи-інтернати',
    area_osvitaa_vydatkydytbudynky:'Видатки місцевого бюджету на дитячі будинки всіх типів та позашкільні заклади освіти',
    area_osvitaa_vydatkyproftech:'Видатки місцевого бюджету на професійно-технічні навчальні заклади ',
    area_osvitaa_vydatkyinshe:'Інші видатки місцевого бюджету на освіту',
    area_osvitaa_vydatkyvyshi:'Видатки місцевого бюджету на вищі навчальні заклади',
    area_derguprav_vydatkyupravlinnya: 'Видатки місцевого бюджету на утримання апаратів управління',
    area_derguprav_vydatkybezpeka: 'Видатки місцевого бюджету на правоохоронну діяльність та забезпечення безпеки держави',
    area_derguprav_vydatkynaosobu: 'Видатки з місцевого бюджету на управління та правоохоронну діяльність в розрахунку на одну особу',
    area_derguprav_pytomavahavydatkiv: 'Питома вага видатків на управління та правоохоронну діяльність у складі видатків місцевого бюджету',
    area_derguprav_kilkistvyborciv: 'Кількість зареєстрованих виборців',
    area_derguprav_pytomavyborciv: 'Питома вага зареєстрованих виборців у складі жителів старше 18 років',
    area_derguprav_vyborciyavka: 'Явка виборців на останніх виборах',
    area_culturee_vydatkynaosobu: 'Видатки з бюджету на духовний та фізичний розвиток людини в розрахунку на одну особу',
    area_culturee_pytomavahavydatkiv: 'Питома вага видатків на духовний та фізичний розвиток людини у складі видатків бюджету',
    area_budgets_vydatkynaosobu: 'Видатки місцевого бюджету на одну особу',
    area_budgets_koefobsluhovborhy: 'Коефіцієнт обслуговування боргу',
    area_budgets_dohodydovydatkiv: 'Співвідношення доходів і видатків місцевого бюджету',
    area_budgets_rentalisovi: 'Рента за використання лісових ресурсів в доходах місцевих бюджетів',
    area_budgets_pdfovdohodah: 'ПДФО в доходах місцевих бюджетів',
    area_budgets_dohodydotaciisubvencii: 'Доходи місцевих бюджетів за рахунок дотацій, субвенцій, інших офіційних трансфертів',
    area_budgets_zempodatokorenda: 'Земельний податок та плата за оренду землі в доходах місцевих бюджетів',
    area_budgets_aktsyznyipodatok: "Акцизний податок з реалізації суб'єктами господарювання роздрібної торгівлі підакцизних товарів",
    area_budgets_edynyipodatok: 'Єдиний податок в доходах місцевих бюджетів',
    area_budgets_podatoknamaino: 'Податок на нерухоме майно в доходах місцевих бюджетів',
    area_budgets_vydatkybudgetu: 'Загальна сума видатків бюджету'



}