export let alias = {
    area_demography_1population: "Загальна кількість населення",
    area_demography_density: 'Щільність населення',
    area_demography_rivenurbanizatsii: 'Рівень урбанізації',
    area_demography_mentowomen: 'Співвідношення чоловіків до жінок',
    area_demography_utrymantsinapratsuuchoho: 'Кількість утриманців на одного працюючого',
    area_demography_zminachiselnostinaselennya: 'Зміна чисельності населення',
    area_sotspol_vyplachenipensii: 'Загальний обсяг виплачених пенсій',
    area_budgets_1dohodymistsevogobudget: 'Доходи місцевих бюджетів',
    area_budgets_pdfonadushu: 'ПДФО на одну особу',
    area_budgets_ttranfertynadushu: 'Трансферти на одну особу',
    area_budgets_zempod: 'Земельний податок та плата за оренду землі на 1 га загальної земельної площі',
    area_budgets_rivpodnavnadushu: 'Рівень податкового навантаження на одну особу',
    area_budgets_rivfinzalejnosti: 'Рівень фінансової залежності місцевого бюджету',
    area_budgets_chastkapodatknadhodj: 'Частка податкових надходжень',
    area_budgets_chastkanepodatknadhodj: 'Частка неподаткових надходжень',
    area_demography_serednviknasel: 'Середній вік населення території',
    area_demography_chastkavikomst60:'Частка осіб віком старше 60 років',
    area_demography_chastkavikomst3560: 'Частка дорослих віком від 35 до 60 років',
    area_demography_chastkavikomst1834:'Частка молоді віком від 18 до 34 років',
    area_demography_chastkavikomst617:'Частка дітей віком від 6 до 17 років',
    area_demography_chastkavikomst05:'Частка дітей віком від 0 до 5 років',
    area_sotspol_vydatkynannadannyapilg:'Видатки на надання пільг',
    area_sotspol_vydatkynannadannyasubs:'Видатки на надання субсидій',
    area_sotspol_kilkistpensioner:'Кількість пенсіонерів',
    point_derguprav_law_sud:'Суди',
    law:'Суди',
    komunal:'Комунальна інфраструктура',
    jytlfond:'Житловий фонд',
    point_infrastructure_jytlfond_jek:'Житлово-експлуатаційні підприємства',
    point_infrastructure_zvyazok_post:'Відділення УДППЗ "Укрпошта"',
    zvyazok:"Зв'язок",
    point_infrastructure_zvyazok_inshi:"Інші оператори поштового зв'язку",
    point_infrastructure_komunal_pidpryemstvbalogoustriy:'Підприємства з благоустрою',
    point_infrastructure_tranport_aviacompany:'Авіакомпанії',
    point_infrastructure_tranport_porty:'Порти',
    tranport:'Транспорт',
    point_demography_obyednannyahromadyan_proffspilky:'Профспілки',
    obyednannyahromadyan:"Об'єднання громадян",
    point_education_naukzaklady_naukovizaklads:'Наукові заклади',
    naukzaklady:'Накові заклади',
    point_ekologyy_ekolnebezpobject_ekolnebezpobjects:"Екологічно небезпечні об'єкти",
    ekolnebezpobject:"Екологічно небезпечні об'єкти",
    point_sotspol_sotshelp_tsentrsocobsl:'Центри соціального обслуговування',
    sotshelp:'Соціальна допомога',
    point_sotspol_sotshelp_tsentrzayn:'Центри зайнятості',
    point_sotspol_sotshelp_inshosotszaklady:'Інші соціальні заклади',
    '1zaklohorzd':"Заклади охорони здоров'я",
    point_ohorzdorov_1zaklohorzd_ambulator:'Амбулаторно-поліклінічні заклади',
    point_ohorzdorov_1zaklohorzd_likarny:'Лікарняні заклади',
    point_ohorzdorov_1zaklohorzd_medsotsz:'Заклади медико-соціального захисту',
    point_ohorzdorov_1zaklohorzd_sanprofzaklad:'Санаторно-профілактичні заклади',
    point_ohorzdorov_1zaklohorzd_sanatoryi:'Санаторно-курортні заклади',
    point_ohorzdorov_1zaklohorzd_zaklperelevkrov:'Заклади переливання крові',
    point_osvitaa_pshk_pozashkilny:'Позашкільні навчальні заклади',
    pshk:'Позашкільні навчальні заклади',
    point_osvitaa_profteh_ptu:'Професійно-технічні навчальні заклади',
    profteh:'Професійно-технічні навчальні заклади',
    point_osvitaa_doshhkilnzakl_doshkilnyzaklady:'Дошкільні навчальні заклади',
    doshhkilnzakl:'Дошкільні навчальні заклади',
    point_osvitaa_heducat_coledg:'Коледжі',
    heducat:'Вищі навчальні заклади',
    point_osvitaa_heducat_institute:'Інститути',
    point_osvitaa_heducat_univercity:'Університети',
    point_osvitaa_heducat_academyi:'Академії',
    point_osvitaa_heducat_zpo:'Заклади післядипломної освіти',
    point_energyy_teploenergy_teplopostachalnypidpr:'Теплопостачальні підприємства',
    teploenergy:'Теплоенергія',
    point_energyy_altobj_alternatyvenergobj:"Об'єкти альтернативної енергетики",
    altobj:"Об'єкти альтернативної енергетики",
    point_energyy_elektroenergy_elektropostachalnicompany:'Електропостачальники',
    elektroenergy:'Електроенергія',
    point_energyy_elektroenergy_pidprvyrobnutstvaenergii:'Підприємства з виробництва електроенергії',
    point_culturee_zakladyfizkultury_zakladyfizkultury:'Заклади фізкультури',
    zakladyfizkultury:'Заклади фізичної культури та спорту',
    point_culturee_vydavntamedia_knygarnivydavnystva:'Видавництва та книгарні',
    vydavntamedia:'Видавництво та медіа',
    point_culturee_vydavntamedia_drukovanizmi:'Друковані ЗМІ',
    point_culturee_vydavntamedia_teleradiocompanii:'Телерадіокомпанії',
    point_culturee_cultzaklady_museum:'Музеї',
    cultzaklady:'Заклади культури',
    point_culturee_cultzaklady_theatre:'Театри',
    point_culturee_cultzaklady_library:'Бібліотеки',
    point_culturee_cultzaklady_inshizaklady:'Інші заклади культури',
    point_osvitaa_1zosh_school1:'ЗОШ I ступенів',
    '1zosh':'Загальноосвітні навчальні заклади',
    point_osvitaa_1zosh_school12:'ЗОШ I-II ступенів',
    point_osvitaa_1zosh_school13:'ЗОШ I-III ступенів',
    point_osvitaa_1zosh_school23:'ЗОШ II-III ступенів',
    point_osvitaa_1zosh_internatschool:'ЗОШ-інтернати',
    point_osvitaa_1zosh_vechirnyschool:'Вечірні школи',
    point_osvitaa_1zosh_spetsializovanyschool:'Спеціалізовані школи',
    point_osvitaa_1zosh_himnasium:'Гімназії',
    point_osvitaa_1zosh_licey:'Ліцеї',
    point_osvitaa_1zosh_colegium:'Колегіуми',
    point_osvitaa_1zosh_spetsialnyschool:'Спеціальні школи',
    area_ekonomika_rivenbezrobittya:'Рівень безробіття',
    area_ekonomika_kilkistbezrobitnyh:'Кількість безробітних',
    area_budgets_chastkadohodvidoperatsiyzkapitalom:'Частка доходів від операцій з капіталом',
    area_sotspol_sumvydatkynasotszahyst:'Загальна сума видатків на соціальний захист',
    area_sotspol_vydatkynasotszahystnadushu:'Видатки на соціальний захист в розрахунку на одну особу',
    area_sotspol_pytomavagavydatkivnasotszahyst:'Питома вага видатків на соціальний захист',
    area_ekonomika_capitalinvest:'Капітальні інвестиції',
    area_ekonomika_vrp:'ВРП у фактичних цінах',
    area_ekonomika_vrpnadushu:'ВРП на одну особу',
    area_ekonomika_ekonomaktyvnnaselennya:'Економічно активне населення',
    area_budgets_kapitalvidbudget:'Капіталовкладення у відсотках від загальних витрат бюджету',
    area_budgets_rentazalisresurs:'Рента за використання лісових ресурсів на 1 га земель лісогосподарського призначення',
    area_zemres_chastkasgzemel:'Частка сільськогосподарських земель',
    area_zemres_chastkspai:'Частка розпайованих земель сільськогосподарського призначення',
    area_zemres_avgareapai:'Середня площа земельної ділянки-паю',
    area_osvitaa_vydatkynadushunas:'Видатки з місцевого бюджету на освіту в розрахунку на одну особу',
    area_osvitaa_pytomavahavydatkiv:'Питома вага видатків на освіту у складі видатків бюджету',
    area_osvitaa_vydatkynashkolyara:'Видатки з місцевого бюджету на загальноосвітні навчальні заклади в розрахунку на 1 дитину шкільного віку',
    area_ohorzdorov_vydatkynadushu:"Видатки місцевого бюджету на охорону здоров'я в розрахунку на одну особу",
    area_ohorzdorov_pytomavahavydatkiv:"Питома вага видатків на охорону здоров'я у складі видатків бюджету",
    area_ohorzdorov_vydatky:"Видатки місцевого бюджету на охорону здоров'я",
    area_osvitaa_vydatky:'Видатки місцевого бюджету на освіту',
    area_culturee_vydatkyvse:'Видатки місцевого бюджету на духовний і фізичний розвиток людини',
    area_culturee_vydbiblioteky:'Видатки місцевого бюджету на бібліотеки',
    area_culturee_vydmuseum:'Видатки місцевого бюджету на музеї, виставки, заповідники',
    area_culturee_vydclub:'Видатки місцевого бюджету на палаци та будинки культури, клуби та інші заклади клубного типу',
    area_culturee_vydteatry:'Видатки місцевого бюджету на творчі спілки, театри, філармонії, гастрольну діяльність',
    area_culturee_vydzakhody:'Видатки місцевого бюджету на інші культурні та мистецькі заклади та заходи',
    area_culturee_vydtv:'Видатки місцевого бюджету на телебачення і радіомовлення',
    area_culturee_vydgazety:'Видатки місцевого бюджету на періодичні видання (газети та журнали)',
    area_culturee_vydknyhovydannya:'Видатки місцевого бюджету на книговидання',
    area_culturee_vydinshe:'Видатки місцевого бюджету на інші засоби масової інформації',
    area_culturee_vydfizra:'Видатки місцевого бюджету на фізичну культуру та спорт'
}