export let alias = {
    area_demography_population: "Загальна кількість населення",
    area_demography_density: 'Щільність населення',
    area_demography_rivenurbanizatsii: 'Рівень урбанізації',
    area_demography_mentowomen: 'Співвідношення чоловіків до жінок',
    area_demography_utrymantsinapratsuuchoho: 'Кількість утриманців на одного працюючого',
    area_demography_zminachiselnostinaselennya: 'Зміна чисельності населення',
    area_sotspol_vyplachenipensii: 'Загальний обсяг виплачених пенсій',
    area_budgets_dohodymistsevogobudget: 'Доходи місцевих бюджетів',
    area_budgets_pdfonadushu: 'ПДФО на душу населення',
    area_budgets_tranfertynadushu: 'Трансферти на душу населення',
    area_budgets_zempod: 'Земельний податок та плата за оренду землі на 1 га загальної земельної площі',
    area_budgets_rivpodnavnadushu: 'Рівень податкового навантаження на душу населення',
    area_budgets_rivfinzalejnosti: 'Рівень фінансової залежності місцевого бюджету',
    area_budgets_chastkapodatknadhodj: 'Частка податкових надходжень',
    area_budgets_chastkanepodatknadhodj: 'Частка неподаткових надходжень',
    area_demography_serednviknasel: 'Середній вік населення території',
    area_demography_chastkavikomst60:'Частка осіб віком старше 60 років',
    area_demography_chastkavikomst3560: 'Частка дорослих віком від 35 до 60 років',
    area_demography_chastkavikomst1834:'Частка молоді віком від 18 до 34 років',
    area_demography_chastkavikomst617:'Частка дітей віком від 6 до 17 років',
    area_demography_chastkavikomst05:'Частка дітей віком від 0 до 5 років',
    area_sotspol_vydatkynannadannyapilg:'Видатки на надання пільг',
    area_sotspol_vydatkynannadannyasubs:'Видатки на надання субсидій',
    area_sotspol_kilkistpensioner:'Кількість пенсіонерів',
    point_derguprav_law_sud:'Суди',
    law:'Суди',
    komunal:'Комунальна інфраструктура',
    jytlfond:'Житловий фонд',
    point_infrastructure_jytlfond_jek:'Житлово-експлуатаційні підприємства',
    point_infrastructure_zvyazok_post:'Відділення УДППЗ "Укрпошта"',
    zvyazok:"Зв'язок",
    point_infrastructure_zvyazok_inshi:"Інші оператори поштового зв'язку",
    point_infrastructure_komunal_pidpryemstvbalogoustriy:'Підприємства з благоустрою',
    point_infrastructure_tranport_aviacompany:'Авіакомпанії',
    point_infrastructure_tranport_porty:'Порти',
    tranport:'Транспорт',
    point_demography_obyednannyahromadyan_proffspilky:'Профспілки',
    obyednannyahromadyan:"Об'єднання громадян",
    point_education_naukzaklady_naukovizaklads:'Наукові заклади',
    naukzaklady:'Накові заклади',
    point_ekologyy_ekolnebezpobject_ekolnebezpobjects:"Екологічно небезпечні об'єкти",
    ekolnebezpobject:"Екологічно небезпечні об'єкти",
    point_sotspol_sotshelp_tsentrsocobsl:'Центри соціального обслуговування',
    sotshelp:'Соціальна допомога',
    point_sotspol_sotshelp_tsentrzayn:'Центри зайнятості',
    point_sotspol_sotshelp_inshosotszaklady:'Інші соціальні заклади',
    zaklohorzd:"Заклади охорони здоров'я",
    point_ohorzdorov_zaklohorzd_ambulator:'Амбулаторно-поліклінічні заклади',
    point_ohorzdorov_zaklohorzd_likarny:'Лікарняні заклади',
    point_ohorzdorov_zaklohorzd_medsotsz:'Заклади медико-соціального захисту',
    point_ohorzdorov_zaklohorzd_sanprofzaklad:'Санаторно-профілактичні заклади',
    point_ohorzdorov_zaklohorzd_sanatoryi:'Санаторно-курортні заклади',
    point_ohorzdorov_zaklohorzd_zaklperelevkrov:'Заклади переливання крові',
    point_osvitaa_vyschi_licey: 'Ліцеї',
    point_osvitaa_vyschi_school_1_33: 'школи І-ІІІ',
    point_osvitaa_vyschi_school_1_3: 'школи І-ІІІ(2)',
    point_osvitaa_vyschi_academyi: 'Академії'

}