export const region = [
    {name: "Автономна Республіка Крим", drilldown: "01"},
    {name: "Рівненська  область", drilldown: "56"},
    {name: "Львівська область", drilldown: "46"},
    {name: "Івано-Франківська область", drilldown: "26"},
    {name: "Закарпатська область", drilldown: "21"},
    {name: "Волинська область", drilldown: "07"},
    {name: "Чернівецька область", drilldown: "73"},
    {name: "Одеська область", drilldown: "51"},
    {name: "Тернопільська область", drilldown: "61"},
    {name: "Житомирська область", drilldown: "18"},
    {name: "Хмельницька область", drilldown: "68"},
    {name: "Херсонська область", drilldown: "65"},
    {name: "Київська область", drilldown: "32"},
    {name: "Миколаївська область", drilldown: "48"},
    {name: "Харківська область", drilldown: "63"},
    {name: "Київ", drilldown: "80"},
    {name: "Вінницька область", drilldown: "05"},
    {name: "Полтавська область", drilldown: "53"},
    {name: "Кіровоградська область", drilldown: "35"},
    {name: "Черкаська область", drilldown: "71"},
    {name: "Луганська область", drilldown: "44"},
    {name: "Дніпропетровська область)", drilldown: "12"},
    {name: "Сумська область", drilldown: "59"},
    {name: "Запорізька область", drilldown: "23"},
    {name: "Севастополь", drilldown: "85"},
    {name: "Чернігівська область", drilldown: "74"},
    {name: "Донецька область", drilldown: "14"}
];

